"""
docrunner/deliveries.py

Sends a finished Output somewhere: email (SMTP) or webhook callback.
Enqueued by the worker (tasks._enqueue_deliveries) as one task per Delivery row.

Deliveries are a separate, independently-retryable concern from generation —
mirroring how PyRunner treats notifications. A failed delivery never affects
the Run's status; it lives or dies on its own row.

Retry model: each attempt increments Delivery.attempts. On failure we re-enqueue
with backoff until MAX_ATTEMPTS, then leave the row FAILED for manual retry from
the UI. django-q2's own retry is intentionally not relied on here so the attempt
count and last_error stay visible in our own table.
"""
import smtplib
import time
from datetime import datetime, timezone
from email.message import EmailMessage
from email.utils import formataddr

import requests
from django.conf import settings
from django_q.tasks import async_task

from docrunner.models import Delivery, Secret, DeliveryStatus, DeliveryKind

MAX_ATTEMPTS = 5
BACKOFF_BASE_SECONDS = 30  # 30s, 60s, 120s, 240s ...
WEBHOOK_TIMEOUT = 30

# MIME types for attaching outputs.
_MIME = {
    "pdf": ("application", "pdf"),
    "docx": ("application", "vnd.openxmlformats-officedocument.wordprocessingml.document"),
    "xlsx": ("application", "vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
}


# ──────────────────────────────────────────────
# Entry point (enqueued with the delivery's UUID)
# ──────────────────────────────────────────────
def send_delivery(delivery_id: str) -> None:
    """Attempt one delivery. Re-enqueues itself with backoff on transient failure."""
    delivery = Delivery.objects.select_related(
        "output", "output__run"
    ).get(id=delivery_id)

    if delivery.status == DeliveryStatus.SENT:
        return  # idempotent: already delivered

    delivery.attempts += 1
    delivery.save(update_fields=["attempts"])

    try:
        if delivery.kind == DeliveryKind.EMAIL:
            _send_email(delivery)
        elif delivery.kind == DeliveryKind.WEBHOOK:
            _send_webhook(delivery)
        else:  # pragma: no cover - guarded by choices
            raise DeliveryError(f"unknown delivery kind: {delivery.kind}")
    except DeliveryError as exc:
        _handle_failure(delivery, str(exc))
        return
    except Exception as exc:  # unexpected — treat as transient, allow retry
        _handle_failure(delivery, f"{type(exc).__name__}: {exc}")
        return

    delivery.status = DeliveryStatus.SENT
    delivery.sent_at = _now()
    delivery.last_error = ""
    delivery.save(update_fields=["status", "sent_at", "last_error"])


# ──────────────────────────────────────────────
# Email (SMTP)
# ──────────────────────────────────────────────
def _send_email(delivery: Delivery) -> None:
    """Send the output as an attachment via SMTP.

    target shape:
        {"to": "x@y.com" | ["a@b.com", ...],
         "subject": "...",            # optional
         "body": "...",               # optional plain-text body
         "from": "Name <a@b.com>"}    # optional; else settings default
    """
    target = delivery.target or {}
    recipients = target.get("to")
    if not recipients:
        raise DeliveryError("email delivery has no 'to' address")
    if isinstance(recipients, str):
        recipients = [recipients]

    output = delivery.output
    run = output.run

    msg = EmailMessage()
    msg["From"] = target.get("from") or _default_from()
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = target.get("subject") or _default_subject(run)

    body = target.get("body") or (
        f"Your document '{output.filename}' is attached.\n\n"
        f"Generated by DocRunner from template '{run.template.name}'."
    )
    msg.set_content(body)

    maintype, subtype = _MIME.get(output.fmt, ("application", "octet-stream"))
    with output.file.open("rb") as fh:
        msg.add_attachment(
            fh.read(), maintype=maintype, subtype=subtype, filename=output.filename
        )

    host = getattr(settings, "SMTP_HOST", None)
    if not host:
        raise DeliveryError("SMTP_HOST is not configured")
    port = int(getattr(settings, "SMTP_PORT", 587))
    user = getattr(settings, "SMTP_USER", "")
    use_tls = bool(getattr(settings, "SMTP_USE_TLS", True))

    try:
        with smtplib.SMTP(host, port, timeout=30) as server:
            if use_tls:
                server.starttls()
            password = _secret(getattr(settings, "SMTP_PASSWORD_SECRET", "SMTP_PASSWORD"))
            if user and password:
                server.login(user, password)
            server.send_message(msg)
    except (smtplib.SMTPException, OSError) as exc:
        # Transient (network/SMTP) — let the retry path handle it.
        raise DeliveryError(f"SMTP send failed: {exc}") from exc


def _default_from() -> str:
    addr = getattr(settings, "DEFAULT_FROM_EMAIL", "docrunner@localhost")
    return formataddr(("DocRunner", addr)) if "<" not in addr else addr


def _default_subject(run) -> str:
    # Factual, unique, no emoji — good deliverability hygiene.
    date = _now().strftime("%Y-%m-%d")
    return f"{run.template.name} - generated {date}"


# ──────────────────────────────────────────────
# Webhook callback
# ──────────────────────────────────────────────
def _send_webhook(delivery: Delivery) -> None:
    """POST a JSON payload to the configured callback URL.

    target shape:
        {"callback_url": "https://...",
         "include_file": true,          # if true, base64 the file into the payload
         "headers": {...},              # optional extra headers
         "secret_name": "WEBHOOK_SIGNING_KEY"}  # optional HMAC signing
    """
    target = delivery.target or {}
    url = target.get("callback_url")
    if not url:
        raise DeliveryError("webhook delivery has no 'callback_url'")

    output = delivery.output
    run = output.run
    payload = {
        "run_id": str(run.id),
        "template": run.template.name,
        "status": run.status,
        "filename": output.filename,
        "format": output.fmt,
        "size_bytes": output.size_bytes,
        "record_index": output.record_index,
        "is_archive": output.is_archive,
    }

    if target.get("include_file"):
        import base64
        with output.file.open("rb") as fh:
            payload["file_base64"] = base64.b64encode(fh.read()).decode()
    else:
        # Otherwise hand back a URL the owner's app can fetch (resolved by the web layer).
        payload["download_path"] = f"/api/runs/{run.id}/output?output_id={output.id}"

    headers = {"Content-Type": "application/json"}
    headers.update(target.get("headers") or {})

    # Optional HMAC signature over the raw body, so the receiver can verify origin.
    body = _json_bytes(payload)
    signing_name = target.get("secret_name")
    if signing_name:
        headers["X-DocRunner-Signature"] = _sign(body, _secret(signing_name))

    try:
        resp = requests.post(url, data=body, headers=headers, timeout=WEBHOOK_TIMEOUT)
    except requests.RequestException as exc:
        raise DeliveryError(f"webhook POST failed: {exc}") from exc

    if resp.status_code >= 400:
        raise DeliveryError(f"webhook returned HTTP {resp.status_code}: {resp.text[:200]}")


# ──────────────────────────────────────────────
# Retry / failure handling
# ──────────────────────────────────────────────
def _handle_failure(delivery: Delivery, error: str) -> None:
    """Record the error; re-enqueue with backoff or give up after MAX_ATTEMPTS."""
    delivery.last_error = error[:2000]
    if delivery.attempts >= MAX_ATTEMPTS:
        delivery.status = DeliveryStatus.FAILED
        delivery.save(update_fields=["status", "last_error"])
        print(f"[ERROR] delivery {delivery.id} gave up after {delivery.attempts} attempts: {error}")
        return

    delivery.status = DeliveryStatus.PENDING
    delivery.save(update_fields=["status", "last_error"])
    delay = BACKOFF_BASE_SECONDS * (2 ** (delivery.attempts - 1))
    print(f"[WARN] delivery {delivery.id} attempt {delivery.attempts} failed; "
          f"retrying in {delay}s: {error}")
    # Schedule the retry. (django-q2 supports a scheduled run via the broker;
    # here we re-enqueue and rely on the next worker pass after the delay.)
    async_task("docrunner.deliveries.send_delivery", str(delivery.id), q_options={"delay": delay})


def retry_delivery(delivery_id: str) -> None:
    """Manual retry hook for the UI: reset a FAILED delivery and re-enqueue."""
    delivery = Delivery.objects.get(id=delivery_id)
    if delivery.status == DeliveryStatus.SENT:
        return
    delivery.status = DeliveryStatus.PENDING
    delivery.attempts = 0
    delivery.last_error = ""
    delivery.save(update_fields=["status", "attempts", "last_error"])
    async_task("docrunner.deliveries.send_delivery", str(delivery.id))


# ──────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────
class DeliveryError(Exception):
    """A delivery attempt failed. Triggers the retry/backoff path."""


def _secret(name: str) -> str:
    """Resolve a Secret by name; missing secret is a hard, non-retryable config error."""
    try:
        return Secret.objects.get(name=name).value
    except Secret.DoesNotExist:
        raise DeliveryError(f"secret '{name}' not found") from None


def _json_bytes(payload: dict) -> bytes:
    import json
    return json.dumps(payload, separators=(",", ":")).encode()


def _sign(body: bytes, key: str) -> str:
    import hashlib
    import hmac
    return "sha256=" + hmac.new(key.encode(), body, hashlib.sha256).hexdigest()


def _now() -> datetime:
    return datetime.now(timezone.utc)
