# Generated by Django 5.2.14 on 2026-06-01 02:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('form', 'Manual form'), ('upload', 'File upload (JSON/CSV)'), ('webhook', 'Inbound webhook'), ('pull', 'Scheduled pull')], max_length=12)),
                ('output_format', models.CharField(choices=[('docx', 'Word (.docx)'), ('xlsx', 'Excel (.xlsx)'), ('pdf', 'PDF')], default='pdf', max_length=8)),
                ('filename_field', models.CharField(blank=True, max_length=100)),
                ('missing_policy', models.CharField(choices=[('error', 'Error on missing field'), ('blank', 'Fill missing field blank')], default='error', max_length=8)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('webhook_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('webhook_secret', models.CharField(blank=True, max_length=128)),
                ('delivery_kind', models.CharField(blank=True, choices=[('email', 'Email'), ('webhook', 'Webhook callback')], max_length=12)),
                ('delivery_config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='outputs/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('fmt', models.CharField(choices=[('docx', 'Word (.docx)'), ('xlsx', 'Excel (.xlsx)'), ('pdf', 'PDF')], max_length=8)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('record_index', models.PositiveIntegerField(blank=True, null=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['record_index'],
            },
        ),
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('_ciphertext', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fmt', models.CharField(choices=[('docx', 'Word (.docx)'), ('xlsx', 'Excel (.xlsx)')], max_length=8)),
                ('file', models.FileField(upload_to='templates/')),
                ('schema', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('webhook', 'Webhook callback')], max_length=12)),
                ('target', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='docrunner.output')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('on_demand', 'On demand'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook')], max_length=12)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial (some records failed)'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('output_format', models.CharField(choices=[('docx', 'Word (.docx)'), ('xlsx', 'Excel (.xlsx)'), ('pdf', 'PDF')], max_length=8)),
                ('input_records', models.JSONField(default=list)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('binding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='docrunner.binding')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='docrunner.template')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.AddField(
            model_name='output',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='docrunner.run'),
        ),
        migrations.AddField(
            model_name='binding',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='docrunner.template'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['status', '-queued_at'], name='docrunner_r_status_308157_idx'),
        ),
    ]
